// This file is regenerated by `pnpm gen:types` from the backend's OpenAPI spec.
// Do not edit by hand. Run the backend on VITE_API_BASE_URL and then run gen:types.

export interface paths {}
export interface components {
  schemas: Record<string, never>;
}
export type operations = Record<string, never>;
