/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verificação de liveness.
         * @description Retorna ``{"status": "ok"}`` quando o processo responde.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verificação de readiness (banco + migrações).
         * @description Confirma conectividade com o banco e migrações em ``head``.
         *
         *     Passos:
         *
         *     1. Executa ``SELECT 1`` — falha aqui significa banco fora do ar.
         *     2. Lê a revisão atual do schema via :class:`MigrationContext`.
         *     3. Compara com o ``head`` declarado em ``migrations/versions/``.
         *
         *     Retorna ``200`` com ``{"status": "ready", ...}`` apenas quando tudo bate;
         *     em qualquer outra situação, ``503`` com detalhes sobre a discrepância.
         */
        get: operations["health_ready_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calculos/pontos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calcula índices anuais para pontos (UC-03 síncrono/assíncrono).
         * @description Roteamento síncrono vs. assíncrono.
         *
         *     - ``len(pontos) <= settings.sincrono_pontos_max`` → 200 com resultados.
         *     - Caso contrário → 202 com ``execucao_id``/``job_id`` (Slice 7).
         *
         *     Ambos os ramos traduzem o payload Pydantic para dataclasses de
         *     ``application`` antes de invocar o caso de uso (ADR-005).
         */
        post: operations["calcular_por_pontos_api_calculos_pontos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/execucoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista execuções com filtros opcionais por cenário/variável/status. */
        get: operations["listar_execucoes_api_execucoes_get"];
        put?: never;
        /**
         * Cria uma execução CORDEX e enfileira o job de processamento.
         * @description Enfileira um job CORDEX. Retorna 202 com ``links.self`` e ``links.job``.
         */
        post: operations["criar_execucao_api_execucoes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/execucoes/{execucao_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtém detalhes de uma execução. */
        get: operations["obter_execucao_api_execucoes__execucao_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/execucoes/{execucao_id}/cancelar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancela uma execução em estado 'pending'. */
        post: operations["cancelar_execucao_api_execucoes__execucao_id__cancelar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/execucoes/estresse-hidrico": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cria uma execução de estresse hídrico e enfileira o job de processamento. */
        post: operations["criar_execucao_estresse_hidrico_api_execucoes_estresse_hidrico_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista jobs com filtros opcionais por status/tipo. */
        get: operations["listar_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtém um job pelo id. */
        get: operations["obter_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reprocessa um job que está em estado 'failed'. */
        post: operations["reprocessar_job_api_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/localizacoes/geocodificar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Geocodifica pares (cidade, UF) usando cache local + IBGE.
         * @description Resolve cada ``(cidade, uf)`` via cache → fuzzy → IBGE.
         *
         *     Entradas não encontradas não bloqueiam o lote — aparecem com
         *     ``metodo="nao_encontrado"``. Se a API do IBGE falhar enquanto uma UF
         *     ainda não foi cacheada, os itens daquela UF voltam com
         *     ``metodo="api_falhou"`` e o endpoint ainda responde 200.
         */
        post: operations["geocodificar_api_localizacoes_geocodificar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/localizacoes/localizar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve pares (lat, lon) em município/UF via shapefile.
         * @description Point-in-polygon sobre a malha de municípios carregada em memória.
         *
         *     Pontos fora do território brasileiro voltam com ``encontrado=false``
         *     e campos de município nulos — o endpoint não bloqueia o lote.
         */
        post: operations["localizar_api_localizacoes_localizar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cobertura/fornecedores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Identifica quais fornecedores têm dados climáticos processados.
         * @description Recebe fornecedores estruturados ou texto legado e devolve cobertura.
         *
         *     Formato legado (ex.: conteúdo do ``Localizacao_fornecedores.xlsx``):
         *
         *     ``MONTE BELO/MG
         *     CONCEICAO DO MATO DENTRO/MG``
         *
         *     Cada linha com ``/`` vira um :class:`FornecedorEntrada`; o
         *     ``identificador`` ecoa a linha original.
         */
        post: operations["cobertura_fornecedores_api_cobertura_fornecedores_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fornecedores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista fornecedores com filtros opcionais por UF e cidade. */
        get: operations["listar_fornecedores_api_fornecedores_get"];
        put?: never;
        /** Cadastra um fornecedor. */
        post: operations["criar_fornecedor_api_fornecedores_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fornecedores/{fornecedor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe de um fornecedor. */
        get: operations["obter_fornecedor_api_fornecedores__fornecedor_id__get"];
        put?: never;
        post?: never;
        /** Remove um fornecedor. */
        delete: operations["remover_fornecedor_api_fornecedores__fornecedor_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fornecedores/importar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Importa fornecedores em lote via arquivo CSV ou XLSX.
         * @description Detecta o formato pela extensão do arquivo.
         *
         *     Linhas sem ``nome``/``cidade``/``uf`` viram erros relatados; duplicatas
         *     (mesmo ``nome+cidade+uf``, existente ou dentro do próprio lote) são
         *     ignoradas. Não faz geocodificação — use ``POST /localizacoes/geocodificar``
         *     depois se precisar preencher coordenadas.
         */
        post: operations["importar_fornecedores_api_fornecedores_importar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resultados": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista resultados com filtros ricos. */
        get: operations["listar_resultados_api_resultados_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resultados/agregados": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agrega resultados por dimensões (media, min, max, count, p50, p95). */
        get: operations["agregar_resultados_api_resultados_agregados_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resultados/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estatísticas globais dos resultados armazenados. */
        get: operations["obter_stats_api_resultados_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resultados/estresse-hidrico": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista resultados de estresse hídrico com filtros opcionais. */
        get: operations["listar_resultados_estresse_hidrico_api_resultados_estresse_hidrico_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/ibge/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recarrega o cache de municípios a partir da API do IBGE.
         * @description Baixa o catálogo completo (~5570 municípios) e atualiza o cache.
         *
         *     Operação cara — uso típico é esporádico (provisionamento, upgrade
         *     anual do IBGE). Nenhuma autenticação por enquanto: o endpoint ``/admin``
         *     serve de placeholder para uma camada futura.
         */
        post: operations["refresh_ibge_api_admin_ibge_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sumário operacional: counters + estatísticas dos resultados.
         * @description Overview para dashboards — counters básicos + distinct values dos índices.
         *
         *     Reúsa :class:`ConsultarStats` (Slice 11) e adiciona contadores simples
         *     sobre as quatro entidades principais. Nenhuma consulta é cara: todos
         *     os ``SELECT COUNT(*)`` rodam direto sobre índices primários.
         */
        get: operations["admin_stats_api_admin_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminStatsResponse
         * @description Corpo do ``GET /admin/stats``.
         *
         *     Reúne os contadores operacionais e as estatísticas já oferecidas por
         *     :class:`~climate_risk.application.resultados.ConsultarStats` — evita que
         *     painéis tenham de bater em dois endpoints para montar um overview.
         */
        AdminStatsResponse: {
            contadores: components["schemas"]["ContadoresAdmin"];
            /** Cenarios */
            cenarios?: string[];
            /** Anos */
            anos?: number[];
            /** Variaveis */
            variaveis?: string[];
            /** Nomes Indices */
            nomes_indices?: string[];
            /** Total Execucoes Com Resultados */
            total_execucoes_com_resultados: number;
            /** Total Resultados */
            total_resultados: number;
        };
        /**
         * AgregacaoResponse
         * @description Corpo do ``GET /resultados/agregados``.
         */
        AgregacaoResponse: {
            /** Agregacao */
            agregacao: string;
            /** Agrupar Por */
            agrupar_por?: string[];
            /** Grupos */
            grupos: components["schemas"]["GrupoAgregadoResponse"][];
        };
        /**
         * BBoxEntrada
         * @description Caixa delimitadora espacial para recorte do grid.
         *
         *     Permite que o retângulo cruze o antimeridiano (``lon_min > lon_max``);
         *     nesse caso, a inclusão em longitude é tratada como duas faixas
         *     disjuntas. Validamos apenas a ordem das latitudes.
         */
        BBoxEntrada: {
            /**
             * Lat Min
             * @description Latitude mínima (inclusiva).
             */
            lat_min: number;
            /**
             * Lat Max
             * @description Latitude máxima (inclusiva).
             */
            lat_max: number;
            /**
             * Lon Min
             * @description Longitude mínima (inclusiva).
             */
            lon_min: number;
            /**
             * Lon Max
             * @description Longitude máxima (inclusiva).
             */
            lon_max: number;
        };
        /** Body_importar_fornecedores_api_fornecedores_importar_post */
        Body_importar_fornecedores_api_fornecedores_importar_post: {
            /** Arquivo */
            arquivo: string;
        };
        /**
         * CalculoPontosAsyncResponse
         * @description Corpo do ``202 Accepted`` quando o lote excede o limite síncrono.
         *
         *     Quando ``len(pontos) > settings.sincrono_pontos_max``, a rota enfileira
         *     um :class:`Job` do tipo ``calcular_pontos`` e devolve esta resposta.
         *     O cliente deve acompanhar o progresso via ``GET /execucoes/{id}`` ou
         *     ``GET /jobs/{id}``.
         */
        CalculoPontosAsyncResponse: {
            /**
             * Execucao Id
             * @description ID da Execucao criada em ``pending``.
             */
            execucao_id: string;
            /**
             * Job Id
             * @description ID do Job enfileirado para processamento.
             */
            job_id: string;
            /**
             * Status
             * @description Status inicial da execução (``pending``).
             */
            status: string;
            /**
             * Total Pontos
             * @description Total de pontos no lote.
             */
            total_pontos: number;
            /**
             * Criado Em
             * @description Timestamp ISO 8601 (UTC) da criação.
             */
            criado_em: string;
            /**
             * Links
             * @description Hyperlinks navegáveis (``self`` para execução, ``job`` para o job).
             */
            links: {
                [key: string]: string;
            };
        };
        /**
         * CalculoPorPontosRequest
         * @description Corpo do ``POST /calculos/pontos``.
         * @example {
         *       "arquivo_nc": "/dados/cordex/rcp45/pr_day_BR_2026-2030.nc",
         *       "cenario": "rcp45",
         *       "parametros_indices": {
         *         "freq_thr_mm": 20,
         *         "heavy20": 20,
         *         "heavy50": 50,
         *         "p95_baseline": {
         *           "fim": 2035,
         *           "inicio": 2026
         *         },
         *         "p95_wet_thr": 1
         *       },
         *       "pontos": [
         *         {
         *           "identificador": "forn-001",
         *           "lat": -23.55,
         *           "lon": -46.63
         *         }
         *       ],
         *       "variavel": "pr"
         *     }
         */
        CalculoPorPontosRequest: {
            /**
             * Arquivo Nc
             * @description Caminho absoluto do arquivo NetCDF.
             */
            arquivo_nc: string;
            /**
             * Cenario
             * @description Rótulo do cenário.
             */
            cenario: string;
            /**
             * Variavel
             * @description Nome da variável climática (MVP: ``pr``).
             * @default pr
             */
            variavel: string;
            /**
             * Pontos
             * @description Pontos a avaliar. Limite síncrono validado na rota.
             */
            pontos: components["schemas"]["PontoEntrada"][];
            /** @description Parâmetros dos índices e do P95. */
            parametros_indices?: components["schemas"]["ParametrosIndicesEntrada"];
        };
        /**
         * CalculoPorPontosResponse
         * @description Corpo do ``200 OK`` do endpoint síncrono.
         *
         *     O endpoint síncrono apenas calcula e devolve os resultados; para
         *     persistir, use o fluxo assíncrono (``202`` via
         *     :class:`CalculoPontosAsyncResponse`) ou o ``POST /execucoes``.
         */
        CalculoPorPontosResponse: {
            /** Cenario */
            cenario: string;
            /** Variavel */
            variavel: string;
            /**
             * Total Pontos
             * @description Quantidade de pontos recebidos.
             */
            total_pontos: number;
            /**
             * Total Resultados
             * @description Quantidade de linhas ``(ponto, ano)`` retornadas.
             */
            total_resultados: number;
            /** Resultados */
            resultados: components["schemas"]["PontoResultado"][];
        };
        /**
         * CoberturaRequest
         * @description Corpo da requisição — aceita formato estruturado OU texto legado.
         *
         *     Exatamente um dos dois campos deve vir preenchido; ambos ou nenhum
         *     resultam em ``422``. O texto legado segue o formato de
         *     ``locais_faltantes_fornecedores.ipynb``: uma linha por fornecedor,
         *     ``CIDADE/UF``, linhas em branco ou sem ``/`` ignoradas.
         */
        CoberturaRequest: {
            /**
             * Fornecedores
             * @description Lista estruturada; mutuamente exclusiva com 'texto_legacy'.
             */
            fornecedores?: components["schemas"]["FornecedorEntradaRequest"][] | null;
            /**
             * Texto Legacy
             * @description Texto bruto no formato CIDADE/UF por linha.
             */
            texto_legacy?: string | null;
        };
        /**
         * CoberturaResponse
         * @description Resposta agregada.
         */
        CoberturaResponse: {
            /** Total */
            total: number;
            /** Com Cobertura */
            com_cobertura: number;
            /** Sem Cobertura */
            sem_cobertura: number;
            /** Itens */
            itens: components["schemas"]["FornecedorCoberturaResponse"][];
        };
        /**
         * ContadoresAdmin
         * @description Contadores simples de entidades persistidas.
         */
        ContadoresAdmin: {
            /** Fornecedores */
            fornecedores: number;
            /** Municipios */
            municipios: number;
            /** Jobs */
            jobs: number;
            /** Execucoes */
            execucoes: number;
        };
        /**
         * CriarExecucaoEstresseHidricoRequest
         * @description Corpo do ``POST /api/execucoes/estresse-hidrico``.
         * @example {
         *       "arquivo_evap": "/dados/cordex/rcp45/evspsbl_day_BR_2026-2035.nc",
         *       "arquivo_pr": "/dados/cordex/rcp45/pr_day_BR_2026-2035.nc",
         *       "arquivo_tas": "/dados/cordex/rcp45/tas_day_BR_2026-2035.nc",
         *       "cenario": "rcp45",
         *       "parametros": {
         *         "limiar_pr_mm_dia": 1,
         *         "limiar_tas_c": 30
         *       }
         *     }
         */
        CriarExecucaoEstresseHidricoRequest: {
            /**
             * Arquivo Pr
             * @description Caminho local do NetCDF de precipitação.
             */
            arquivo_pr: string;
            /**
             * Arquivo Tas
             * @description Caminho local do NetCDF de temperatura.
             */
            arquivo_tas: string;
            /**
             * Arquivo Evap
             * @description Caminho local do NetCDF de evaporação.
             */
            arquivo_evap: string;
            /**
             * Cenario
             * @description Rótulo CORDEX (ex.: 'rcp45', 'rcp85', 'ssp245').
             */
            cenario: string;
            parametros?: components["schemas"]["ParametrosIndicesEstresseHidricoSchema"];
        };
        /**
         * CriarExecucaoEstresseHidricoResponse
         * @description Corpo do ``202 Accepted``.
         */
        CriarExecucaoEstresseHidricoResponse: {
            /** Execucao Id */
            execucao_id: string;
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Criado Em */
            criado_em: string;
            /**
             * Links
             * @description HATEOAS: ``self`` e ``job``.
             * @example {
             *       "job": "/api/jobs/job_01HX...",
             *       "self": "/api/execucoes/exec_01HX..."
             *     }
             */
            links: {
                [key: string]: string;
            };
        };
        /**
         * CriarExecucaoRequest
         * @description Corpo do ``POST /execucoes``.
         * @example {
         *       "arquivo_nc": "/dados/cordex/rcp45/pr_day_BR_2026-2030.nc",
         *       "bbox": {
         *         "lat_max": 5.5,
         *         "lat_min": -33.75,
         *         "lon_max": -34.8,
         *         "lon_min": -74
         *       },
         *       "cenario": "rcp45",
         *       "parametros_indices": {
         *         "freq_thr_mm": 20,
         *         "heavy20": 20,
         *         "heavy50": 50,
         *         "p95_baseline": {
         *           "fim": 2035,
         *           "inicio": 2026
         *         },
         *         "p95_wet_thr": 1
         *       },
         *       "variavel": "pr"
         *     }
         */
        CriarExecucaoRequest: {
            /**
             * Arquivo Nc
             * @description Caminho local para o arquivo .nc.
             */
            arquivo_nc: string;
            /**
             * Cenario
             * @description Rótulo do cenário.
             */
            cenario: string;
            /**
             * Variavel
             * @description Nome da variável climática. MVP: apenas 'pr'.
             * @default pr
             */
            variavel: string;
            /** @description Recorte espacial opcional. None processa a grade inteira. */
            bbox?: components["schemas"]["BBoxEntrada"] | null;
            /** @description Parâmetros dos índices e do P95. */
            parametros_indices?: components["schemas"]["ParametrosIndicesEntrada"];
            /** @description Baseline do P95. Quando ``null``, prevalece ``parametros_indices.p95_baseline``; ambos ``null`` desativam o P95. */
            p95_baseline?: components["schemas"]["PeriodoBaselineEntrada"] | null;
        };
        /**
         * CriarExecucaoResponse
         * @description Corpo do ``202 Accepted`` de ``POST /execucoes``.
         */
        CriarExecucaoResponse: {
            /** Execucao Id */
            execucao_id: string;
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Criado Em */
            criado_em: string;
            /**
             * Links
             * @description HATEOAS: ``self`` e ``job``.
             * @example {
             *       "job": "/api/jobs/job_01HX...",
             *       "self": "/api/execucoes/exec_01HX..."
             *     }
             */
            links: {
                [key: string]: string;
            };
        };
        /**
         * EntradaLocalizacaoSchema
         * @description Par (cidade, uf) digitado pelo usuário.
         */
        EntradaLocalizacaoSchema: {
            /**
             * Cidade
             * @description Nome da cidade.
             */
            cidade: string;
            /**
             * Uf
             * @description Sigla da UF (2 letras).
             */
            uf: string;
        };
        /** ErroLinhaResponse */
        ErroLinhaResponse: {
            /** Linha */
            linha: number;
            /** Motivo */
            motivo: string;
        };
        /**
         * EstatisticasResponse
         * @description Corpo do ``GET /resultados/stats``.
         */
        EstatisticasResponse: {
            /** Cenarios */
            cenarios?: string[];
            /** Anos */
            anos?: number[];
            /** Variaveis */
            variaveis?: string[];
            /** Nomes Indices */
            nomes_indices?: string[];
            /** Total Execucoes Com Resultados */
            total_execucoes_com_resultados: number;
            /** Total Resultados */
            total_resultados: number;
        };
        /**
         * ExecucaoResumo
         * @description Representação resumida de :class:`Execucao` na API.
         */
        ExecucaoResumo: {
            /** Id */
            id: string;
            /** Cenario */
            cenario: string;
            /** Variavel */
            variavel: string;
            /** Arquivo Origem */
            arquivo_origem: string;
            /** Tipo */
            tipo: string;
            /** Status */
            status: string;
            /** Criado Em */
            criado_em: string;
            /** Concluido Em */
            concluido_em: string | null;
            /** Job Id */
            job_id: string | null;
        };
        /**
         * FornecedorCoberturaResponse
         * @description Resposta unitária.
         */
        FornecedorCoberturaResponse: {
            /** Identificador */
            identificador: string;
            /** Cidade Entrada */
            cidade_entrada: string;
            /** Uf Entrada */
            uf_entrada: string;
            /** Tem Cobertura */
            tem_cobertura: boolean;
            /** Municipio Id */
            municipio_id?: number | null;
            /** Nome Canonico */
            nome_canonico?: string | null;
            /**
             * Motivo Nao Encontrado
             * @description Quando tem_cobertura=False: 'municipio_nao_geocodificado' ou 'sem_dados_climaticos'.
             */
            motivo_nao_encontrado?: string | null;
        };
        /**
         * FornecedorEntradaRequest
         * @description Fornecedor em formato estruturado.
         */
        FornecedorEntradaRequest: {
            /** Identificador */
            identificador: string;
            /** Cidade */
            cidade: string;
            /** Uf */
            uf: string;
        };
        /**
         * FornecedorRequest
         * @description Corpo de ``POST /fornecedores``.
         */
        FornecedorRequest: {
            /** Nome */
            nome: string;
            /** Cidade */
            cidade: string;
            /** Uf */
            uf: string;
            /** Identificador Externo */
            identificador_externo?: string | null;
            /** Municipio Id */
            municipio_id?: number | null;
        };
        /**
         * FornecedorResponse
         * @description Representação de um :class:`Fornecedor` em JSON.
         */
        FornecedorResponse: {
            /** Id */
            id: string;
            /** Nome */
            nome: string;
            /** Cidade */
            cidade: string;
            /** Uf */
            uf: string;
            /** Identificador Externo */
            identificador_externo?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Municipio Id */
            municipio_id?: number | null;
            /** Criado Em */
            criado_em: string;
            /** Atualizado Em */
            atualizado_em: string;
        };
        /**
         * GeocodificarRequest
         * @description Corpo da requisição ``POST /localizacoes/geocodificar``.
         */
        GeocodificarRequest: {
            /**
             * Localizacoes
             * @description Lote de entradas a geocodificar.
             */
            localizacoes: components["schemas"]["EntradaLocalizacaoSchema"][];
        };
        /**
         * GeocodificarResponse
         * @description Resposta agregada de ``POST /localizacoes/geocodificar``.
         */
        GeocodificarResponse: {
            /** Total */
            total: number;
            /** Encontrados */
            encontrados: number;
            /** Nao Encontrados */
            nao_encontrados: number;
            /** Itens */
            itens: components["schemas"]["LocalizacaoGeocodificadaSchema"][];
        };
        /**
         * GrupoAgregadoResponse
         * @description Uma linha do ``GET /resultados/agregados``.
         */
        GrupoAgregadoResponse: {
            /**
             * Grupo
             * @description Chaves do GROUP BY com os valores daquele bucket.
             */
            grupo?: {
                [key: string]: string | number;
            };
            /**
             * Valor
             * @description Resultado da função; null se não definido para o grupo.
             */
            valor: number | null;
            /** N Amostras */
            n_amostras: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IndicesResposta
         * @description Conjunto de índices anuais retornado por ponto/ano.
         */
        IndicesResposta: {
            /** Wet Days */
            wet_days: number;
            /** Sdii */
            sdii: number | null;
            /** Rx1Day */
            rx1day: number | null;
            /** Rx5Day */
            rx5day: number | null;
            /** R20Mm */
            r20mm: number;
            /** R50Mm */
            r50mm: number;
            /** R95Ptot Mm */
            r95ptot_mm: number | null;
            /** R95Ptot Frac */
            r95ptot_frac: number | null;
        };
        /**
         * JobResponse
         * @description Representação HTTP de um :class:`Job`.
         */
        JobResponse: {
            /**
             * Id
             * @description Identificador ULID prefixado (``job_...``).
             */
            id: string;
            /**
             * Tipo
             * @description Categoria do job (ex.: ``noop``).
             */
            tipo: string;
            /**
             * Payload
             * @description Dados de entrada do job.
             */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Status
             * @description Um de: pending, running, completed, failed, canceled.
             */
            status: string;
            /** Tentativas */
            tentativas: number;
            /** Max Tentativas */
            max_tentativas: number;
            /**
             * Criado Em
             * Format: date-time
             */
            criado_em: string;
            /** Iniciado Em */
            iniciado_em?: string | null;
            /** Concluido Em */
            concluido_em?: string | null;
            /** Heartbeat */
            heartbeat?: string | null;
            /** Erro */
            erro?: string | null;
            /** Proxima Tentativa Em */
            proxima_tentativa_em?: string | null;
        };
        /**
         * ListaExecucoesResponse
         * @description Corpo do ``GET /execucoes``.
         */
        ListaExecucoesResponse: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["ExecucaoResumo"][];
        };
        /**
         * ListaJobsResponse
         * @description Resposta paginada de ``GET /jobs``.
         */
        ListaJobsResponse: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items?: components["schemas"]["JobResponse"][];
        };
        /**
         * ListarResultadosEstresseHidricoResponse
         * @description Corpo do ``GET /api/resultados/estresse-hidrico``.
         */
        ListarResultadosEstresseHidricoResponse: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["ResultadoEstresseHidricoSchema"][];
        };
        /**
         * LocalizacaoGeocodificadaSchema
         * @description Resposta unitária da geocodificação.
         */
        LocalizacaoGeocodificadaSchema: {
            /** Cidade Entrada */
            cidade_entrada: string;
            /** Uf */
            uf: string;
            /**
             * Municipio Id
             * @description Código IBGE (7 dígitos) do município resolvido, se houver.
             */
            municipio_id?: number | null;
            /**
             * Nome Canonico
             * @description Nome oficial do município segundo o IBGE.
             */
            nome_canonico?: string | null;
            /**
             * Lat
             * @description Latitude do centroide em graus decimais (EPSG:4326).
             */
            lat?: number | null;
            /**
             * Lon
             * @description Longitude do centroide em graus decimais (EPSG:4326).
             */
            lon?: number | null;
            /**
             * Metodo
             * @description Caminho que resolveu a entrada: 'cache_exato', 'cache_fuzzy', 'ibge', 'nao_encontrado' ou 'api_falhou'.
             */
            metodo: string;
        };
        /**
         * LocalizarPontosRequest
         * @description Corpo da requisição ``POST /localizacoes/localizar``.
         */
        LocalizarPontosRequest: {
            /**
             * Pontos
             * @description Lote de pontos. Operação é sempre síncrona.
             */
            pontos: components["schemas"]["PontoParaLocalizarRequest"][];
        };
        /**
         * LocalizarPontosResponse
         * @description Resposta agregada.
         */
        LocalizarPontosResponse: {
            /** Total */
            total: number;
            /** Encontrados */
            encontrados: number;
            /** Itens */
            itens: components["schemas"]["PontoLocalizadoResponse"][];
        };
        /**
         * PaginaFornecedoresResponse
         * @description Resposta paginada de ``GET /fornecedores``.
         */
        PaginaFornecedoresResponse: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Itens */
            itens: components["schemas"]["FornecedorResponse"][];
        };
        /**
         * PaginaResultadosResponse
         * @description Corpo do ``GET /resultados``.
         */
        PaginaResultadosResponse: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["ResultadoResponse"][];
        };
        /**
         * ParametrosIndicesEntrada
         * @description Parâmetros configuráveis do cálculo.
         */
        ParametrosIndicesEntrada: {
            /**
             * Freq Thr Mm
             * @description Limiar T (mm/dia) para wet_days/sdii.
             * @default 20
             */
            freq_thr_mm: number;
            /**
             * P95 Wet Thr
             * @description Limiar de dia chuvoso (mm/dia) para o cálculo do P95.
             * @default 1
             */
            p95_wet_thr: number;
            /**
             * Heavy20
             * @description Limiar para r20mm (mm/dia).
             * @default 20
             */
            heavy20: number;
            /**
             * Heavy50
             * @description Limiar para r50mm (mm/dia).
             * @default 50
             */
            heavy50: number;
            /** @description Baseline do P95; ``null`` desativa o cálculo do P95. */
            p95_baseline?: components["schemas"]["PeriodoBaselineEntrada"] | null;
        };
        /**
         * ParametrosIndicesEstresseHidricoSchema
         * @description Limiares dos índices (espelha o dataclass de domínio).
         */
        ParametrosIndicesEstresseHidricoSchema: {
            /**
             * Limiar Pr Mm Dia
             * @description Teto de precipitação para considerar um dia 'seco' (mm/dia).
             * @default 1
             */
            limiar_pr_mm_dia: number;
            /**
             * Limiar Tas C
             * @description Piso de temperatura para considerar um dia 'quente' (°C).
             * @default 30
             */
            limiar_tas_c: number;
        };
        /**
         * PeriodoBaselineEntrada
         * @description Intervalo fechado de anos usado como baseline para o P95.
         */
        PeriodoBaselineEntrada: {
            /**
             * Inicio
             * @description Ano inicial (inclusivo).
             */
            inicio: number;
            /**
             * Fim
             * @description Ano final (inclusivo).
             */
            fim: number;
        };
        /**
         * PontoEntrada
         * @description Coordenada de entrada para um ponto (fornecedor, sítio, etc.).
         */
        PontoEntrada: {
            /**
             * Lat
             * @description Latitude em graus decimais.
             */
            lat: number;
            /**
             * Lon
             * @description Longitude em graus decimais.
             */
            lon: number;
            /**
             * Identificador
             * @description Rótulo opcional (ex.: ``forn-001``) devolvido em cada resultado.
             */
            identificador?: string | null;
        };
        /**
         * PontoLocalizadoResponse
         * @description Resposta unitária.
         */
        PontoLocalizadoResponse: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Identificador */
            identificador?: string | null;
            /** Encontrado */
            encontrado: boolean;
            /** Municipio Id */
            municipio_id?: number | null;
            /** Uf */
            uf?: string | null;
            /** Nome Municipio */
            nome_municipio?: string | null;
        };
        /**
         * PontoParaLocalizarRequest
         * @description Par (lat, lon) a ser resolvido em município.
         */
        PontoParaLocalizarRequest: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /**
             * Identificador
             * @description Opcional — ecoado de volta para correlação do cliente.
             */
            identificador?: string | null;
        };
        /**
         * PontoResultado
         * @description Uma linha de resultado — um ponto em um ano.
         */
        PontoResultado: {
            /** Identificador */
            identificador: string | null;
            /** Lat Input */
            lat_input: number;
            /** Lon Input */
            lon_input: number;
            /** Lat Grid */
            lat_grid: number;
            /** Lon Grid */
            lon_grid: number;
            /** Ano */
            ano: number;
            indices: components["schemas"]["IndicesResposta"];
        };
        /**
         * ProblemDetails
         * @description Alias público e mais verboso de :class:`ErroRfc7807`.
         *
         *     Usado nas declarações ``responses={...}`` dos endpoints para que o
         *     OpenAPI exponha o formato RFC 7807 nas respostas de erro (``4xx``/
         *     ``5xx``). Mantemos ambos os nomes: ``ErroRfc7807`` é o identificador
         *     interno e ``ProblemDetails`` é a exposição pública no schema.
         */
        ProblemDetails: {
            /**
             * Type
             * @description URI que identifica o tipo de problema.
             * @default about:blank
             */
            type: string;
            /**
             * Title
             * @description Resumo legível do problema.
             */
            title: string;
            /**
             * Status
             * @description Código HTTP associado.
             */
            status: number;
            /**
             * Detail
             * @description Explicação específica para esta ocorrência.
             */
            detail?: string | null;
            /**
             * Instance
             * @description URI da ocorrência (normalmente ``request.url.path``).
             */
            instance?: string | null;
            /**
             * Correlation Id
             * @description Identificador propagado no header ``X-Correlation-ID``.
             */
            correlation_id?: string | null;
        };
        /**
         * RefreshIBGEResponse
         * @description Resposta de ``POST /admin/ibge/refresh``.
         */
        RefreshIBGEResponse: {
            /** Total Municipios */
            total_municipios: number;
            /** Com Centroide */
            com_centroide: number;
            /** Sem Centroide */
            sem_centroide: number;
        };
        /**
         * ResultadoEstresseHidricoSchema
         * @description Item de :class:`ListarResultadosEstresseHidricoResponse`.
         */
        ResultadoEstresseHidricoSchema: {
            /** Id */
            id: string;
            /** Execucao Id */
            execucao_id: string;
            /** Municipio Id */
            municipio_id: number;
            /** Ano */
            ano: number;
            /** Cenario */
            cenario: string;
            /** Frequencia Dias Secos Quentes */
            frequencia_dias_secos_quentes: number;
            /** Intensidade Mm Dia */
            intensidade_mm_dia: number;
            /** Nome Municipio */
            nome_municipio?: string | null;
            /** Uf */
            uf?: string | null;
        };
        /**
         * ResultadoImportacaoResponse
         * @description Resposta de ``POST /fornecedores/importar``.
         */
        ResultadoImportacaoResponse: {
            /** Total Linhas */
            total_linhas: number;
            /** Importados */
            importados: number;
            /** Duplicados */
            duplicados: number;
            /** Erros */
            erros: components["schemas"]["ErroLinhaResponse"][];
        };
        /**
         * ResultadoResponse
         * @description Representação de :class:`ResultadoIndice` na API.
         */
        ResultadoResponse: {
            /** Id */
            id: string;
            /** Execucao Id */
            execucao_id: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Lat Input */
            lat_input?: number | null;
            /** Lon Input */
            lon_input?: number | null;
            /** Ano */
            ano: number;
            /** Nome Indice */
            nome_indice: string;
            /** Valor */
            valor: number | null;
            /** Unidade */
            unidade?: string | null;
            /** Municipio Id */
            municipio_id?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_ready_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    calcular_por_pontos_api_calculos_pontos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalculoPorPontosRequest"];
            };
        };
        responses: {
            /** @description Lote pequeno processado de forma síncrona. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculoPorPontosResponse"];
                };
            };
            /** @description Lote grande (> ``sincrono_pontos_max`` pontos): job enfileirado. Acompanhe via ``GET /execucoes/{id}``. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculoPontosAsyncResponse"];
                };
            };
            /** @description Arquivo NetCDF não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Erro de validação ou dataset inválido. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Erro interno. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listar_execucoes_api_execucoes_get: {
        parameters: {
            query?: {
                cenario?: string | null;
                variavel?: string | null;
                status?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaExecucoesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_execucao_api_execucoes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriarExecucaoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriarExecucaoResponse"];
                };
            };
            /** @description Arquivo NetCDF não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Erro de validação do corpo. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    obter_execucao_api_execucoes__execucao_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execucao_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecucaoResumo"];
                };
            };
            /** @description Execução não encontrada. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancelar_execucao_api_execucoes__execucao_id__cancelar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execucao_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecucaoResumo"];
                };
            };
            /** @description Execução não encontrada. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Estado atual não permite cancelamento. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_execucao_estresse_hidrico_api_execucoes_estresse_hidrico_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriarExecucaoEstresseHidricoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriarExecucaoEstresseHidricoResponse"];
                };
            };
            /** @description Algum dos três arquivos NetCDF não foi encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Erro de validação do corpo. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listar_jobs_api_jobs_get: {
        parameters: {
            query?: {
                status?: string | null;
                tipo?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaJobsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Job não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reprocessar_job_api_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Job não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Estado atual não permite retry. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    geocodificar_api_localizacoes_geocodificar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeocodificarRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeocodificarResponse"];
                };
            };
            /** @description Erro de validação. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description API do IBGE indisponível. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    localizar_api_localizacoes_localizar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocalizarPontosRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalizarPontosResponse"];
                };
            };
            /** @description Erro de validação. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Shapefile não configurado. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    cobertura_fornecedores_api_cobertura_fornecedores_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoberturaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoberturaResponse"];
                };
            };
            /** @description Erro de validação. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description API do IBGE indisponível. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listar_fornecedores_api_fornecedores_get: {
        parameters: {
            query?: {
                uf?: string | null;
                cidade?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaFornecedoresResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_fornecedor_api_fornecedores_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FornecedorRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FornecedorResponse"];
                };
            };
            /** @description Conflito de integridade. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Erro de validação do corpo. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    obter_fornecedor_api_fornecedores__fornecedor_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fornecedor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FornecedorResponse"];
                };
            };
            /** @description Fornecedor não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remover_fornecedor_api_fornecedores__fornecedor_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fornecedor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fornecedor não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    importar_fornecedores_api_fornecedores_importar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_importar_fornecedores_api_fornecedores_importar_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoImportacaoResponse"];
                };
            };
            /** @description Formato de arquivo não suportado. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_resultados_api_resultados_get: {
        parameters: {
            query?: {
                /** @description Filtra por execução. */
                execucao_id?: string | null;
                /** @description Cenário da execução. */
                cenario?: string | null;
                /** @description Variável climática. */
                variavel?: string | null;
                /** @description Ano exato. */
                ano?: number | null;
                /** @description Ano mínimo inclusivo. */
                ano_min?: number | null;
                /** @description Ano máximo inclusivo. */
                ano_max?: number | null;
                /** @description Lista CSV de nomes de índice (ex.: 'PRCPTOT,CDD'). */
                nomes_indices?: string | null;
                lat_min?: number | null;
                lat_max?: number | null;
                lon_min?: number | null;
                lon_max?: number | null;
                /** @description Exige centro_lat/lon. */
                raio_km?: number | null;
                centro_lat?: number | null;
                centro_lon?: number | null;
                uf?: string | null;
                municipio_id?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaResultadosResponse"];
                };
            };
            /** @description Combinação inválida de filtros. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    agregar_resultados_api_resultados_agregados_get: {
        parameters: {
            query?: {
                /** @description Função de agregação. */
                agregacao?: string;
                /** @description Lista CSV de dimensões (ano, cenario, variavel, nome_indice, municipio). Vazio = agregação global. */
                agrupar_por?: string | null;
                execucao_id?: string | null;
                cenario?: string | null;
                variavel?: string | null;
                ano?: number | null;
                ano_min?: number | null;
                ano_max?: number | null;
                nomes_indices?: string | null;
                lat_min?: number | null;
                lat_max?: number | null;
                lon_min?: number | null;
                lon_max?: number | null;
                raio_km?: number | null;
                centro_lat?: number | null;
                centro_lon?: number | null;
                uf?: string | null;
                municipio_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgregacaoResponse"];
                };
            };
            /** @description Combinação inválida de filtros. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    obter_stats_api_resultados_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstatisticasResponse"];
                };
            };
        };
    };
    listar_resultados_estresse_hidrico_api_resultados_estresse_hidrico_get: {
        parameters: {
            query?: {
                execucao_id?: string | null;
                cenario?: string | null;
                ano?: number | null;
                ano_min?: number | null;
                ano_max?: number | null;
                municipio_id?: number | null;
                uf?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListarResultadosEstresseHidricoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_ibge_api_admin_ibge_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshIBGEResponse"];
                };
            };
            /** @description API do IBGE indisponível. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    admin_stats_api_admin_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStatsResponse"];
                };
            };
        };
    };
}
